export const HOBBIES_LIST = [
  { label: "Sports", value: "Sports" },
  { label: "Reading", value: "Reading" },
  { label: "Gardening", value: "Gardening" },
  { label: "Cooking", value: "Cooking" },
  { label: "Baking", value: "Baking" },
  { label: "Photography", value: "Photography" },
  { label: "Writing", value: "Writing" },
  { label: "Drawing", value: "Drawing" },
  { label: "Painting", value: "Painting" },
  { label: "Knitting", value: "Knitting" },
  { label: "Crocheting", value: "Crocheting" },
  { label: "Fishing", value: "Fishing" },
  { label: "Hiking", value: "Hiking" },
  { label: "Cycling", value: "Cycling" },
  { label: "Bird Watching", value: "Bird Watching" },
  { label: "Astronomy", value: "Astronomy" },
  {
    label: "Playing Musical Instruments",
    value: "Playing Musical Instruments",
  },
  { label: "Singing", value: "Singing" },
  { label: "Dancing", value: "Dancing" },
  { label: "Yoga", value: "Yoga" },
  { label: "Meditation", value: "Meditation" },
  { label: "Collecting (e.g., stamps, coins, art)", value: "Collecting" },
  { label: "Model Building", value: "Model Building" },
  { label: "DIY Projects", value: "DIY Projects" },
  { label: "Video Gaming", value: "Video Gaming" },
  { label: "Board Gaming", value: "Board Gaming" },
  { label: "Puzzle Solving", value: "Puzzle Solving" },
  { label: "Traveling", value: "Traveling" },
  { label: "Learning New Languages", value: "Learning New Languages" },
  { label: "Volunteering", value: "Volunteering" },
];
