export const GRAPH_WIDTH_TO_SCREEN_WIDTH_RATIO = 0.9;
export const DEFAULT_GRAPH_HEIGHT = 220;

const STAT_POLLING_INTERVAL_SECONDS = 120;
const MS_TO_SECONDS = 1000;
export const STAT_POLLING_INTERVAL = STAT_POLLING_INTERVAL_SECONDS * MS_TO_SECONDS;
